//
//Generated by DELTADATOR\GS0445 at 26/03/2009 9.03.13
//

using System;

namespace it.dedagroup.GVC.Repository.rtier.Service
{
	/// <summary>
	/// Description of GVCDSOTTOCATEGORIE
	/// </summary>
	public partial class GVCDSOTTOCATEGORIE
	{
		private System.Int32 _iDOBJ;
		private System.String _dESCRIZIONE;
		private System.Int32 _fLAG_ATTIVO;

		/// <summary>
		/// Default constructor
		/// </summary>
		public GVCDSOTTOCATEGORIE(){}

		/// <summary>
		/// Identificativo del record
		/// The field is mandatory.
		/// </summary>
		public System.Int32 IDOBJ
		{
			get
			{
				return _iDOBJ;
			}
			set
			{
				_iDOBJ = value;
			}
		}

		/// <summary>
		/// Descrizione sottocategoria
		/// The field is mandatory.
		/// </summary>
		public System.String DESCRIZIONE
		{
			get
			{
				return _dESCRIZIONE;
			}
			set
			{
				_dESCRIZIONE = value;
			}
		}

		/// <summary>
		/// Flag attivo 0=attivo 1=non attivo
		/// The field is mandatory.
		/// </summary>
		public System.Int32 FLAG_ATTIVO
		{
			get
			{
				return _fLAG_ATTIVO;
			}
			set
			{
				_fLAG_ATTIVO = value;
			}
		}

	}
}