//
//Generated by DELTADATOR\GS0445 at 26/03/2009 9.03.13
//

using System;

namespace it.dedagroup.GVC.Repository.rtier.Service
{
	/// <summary>
	/// Description of GVCDATECO
	/// </summary>
	public partial class GVCDATECO
	{
		private System.Int32 _iDOBJ;
		private System.String _cODICE;
		private System.String _dESCRIZIONE;
		private System.Boolean _dESCRIZIONENull = true;

		/// <summary>
		/// Default constructor
		/// </summary>
		public GVCDATECO(){}

		/// <summary>
		/// Ientificativo del record
		/// The field is mandatory.
		/// </summary>
		public System.Int32 IDOBJ
		{
			get
			{
				return _iDOBJ;
			}
			set
			{
				_iDOBJ = value;
			}
		}

		/// <summary>
		/// Codice attività
		/// The field is mandatory.
		/// </summary>
		public System.String CODICE
		{
			get
			{
				return _cODICE;
			}
			set
			{
				_cODICE = value;
			}
		}

		/// <summary>
		/// Descrizione attività
		/// </summary>
		public System.String DESCRIZIONE
		{
			get
			{
				if(IsDESCRIZIONENull)
					throw new InvalidOperationException("Impossibile leggere il dato in quanto vale DBNull.");
				return _dESCRIZIONE;
			}
			set
			{
				_dESCRIZIONENull = false;
				_dESCRIZIONE = value;
			}
		}

		/// <summary>
		/// Return true if field is null, otherwise false.
		/// </summary>
		public bool IsDESCRIZIONENull
		{
			get
			{
				return _dESCRIZIONENull;
			}
			set
			{
				_dESCRIZIONENull = value;
			}
		}

		/// <summary>
		///  This property is intend to use with string and integer fields 
		///  that can contain nullable values. 
		///  It is read only. 
		/// </summary>
		/// <returns>The value of the field or String.Empty/-1</returns>
		public System.String DESCRIZIONESafe
		{
			get
			{
				if (IsDESCRIZIONENull)
					return System.String.Empty;
				return DESCRIZIONE;
			}
		}

	}
}