//
//Generated by gvc at 26/03/2009 9.03.13
//

using System;
using System.Data;
using System.Text;

namespace it.dedagroup.GVC.Repository.rtier.Service
{
	/// <summary>
	/// Data Access Layer for the object GVCDDATI
	/// </summary>
	public partial class GVCDDATICollection
	{
		/// <summary>
		/// Returns the Database Name of the field IDOBJ.
		///The field is mandatory.
		/// </summary>
		public const string IDOBJColumnName = "IDOBJ";
		/// <summary>
		/// Returns the Database Name of the field VALMINQUOTA.
		/// </summary>
		public const string VALMINQUOTAColumnName = "VALMINQUOTA";
		/// <summary>
		/// Returns the Database Name of the field VALMAXQUOTA.
		/// </summary>
		public const string VALMAXQUOTAColumnName = "VALMAXQUOTA";
		/// <summary>
		/// Returns the Database Name of the field VALMINAZIONE.
		/// </summary>
		public const string VALMINAZIONEColumnName = "VALMINAZIONE";
		/// <summary>
		/// Returns the Database Name of the field VALMAXAZIONE.
		/// </summary>
		public const string VALMAXAZIONEColumnName = "VALMAXAZIONE";
		/// <summary>
		/// Returns the Database Name of the field PERCENTUALE_CNP.
		/// </summary>
		public const string PERCENTUALE_CNPColumnName = "PERCENTUALE_CNP";
		/// <summary>
		/// Returns the Database Name of the field PERCENTUALE_IVA.
		/// </summary>
		public const string PERCENTUALE_IVAColumnName = "PERCENTUALE_IVA";
		/// <summary>
		/// Returns the Database Name of the field PERCENTUALE_PAT.
		/// </summary>
		public const string PERCENTUALE_PATColumnName = "PERCENTUALE_PAT";

		/// <summary>
		/// Gateway to the Database
		/// </summary>
		protected GVC _db;

		/// <summary>
		/// Default constructor
		/// </summary>
		/// <param name="db">Istance of the Database</param>
		public GVCDDATICollection(GVC db)
		{
			_db = db;
		}

		/// <summary>
		/// Property for the Database
		/// </summary>
		protected GVC Database
		{
			get
			{
				return _db;
			}
		}

		/// <summary>
		/// Returns an array containing all the objects GVCDDATI
		/// </summary>
		/// <returns>Array of objects GVCDDATI</returns>
		public virtual GVCDDATI[] GetAll()
		{
			return MapRecords(CreateGetAllCommand());
		}

		/// <summary>
		/// Returns a DataTable containing all the objects GVCDDATI
		/// </summary>
		/// <returns>DataTable of objects GVCDDATI</returns>
		public virtual DataTable GetAllAsDataTable()
		{
			return MapRecordsToDataTable(CreateGetAllCommand());
		}

		/// <summary>
		/// Returns an IDbCommand to get all the objects GVCDDATI
		/// </summary>
		/// <returns>Istance of IDbCommand</returns>
		protected virtual IDbCommand CreateGetAllCommand()
		{
			return CreateGetCommand(null, null);
		}

		/// <summary>
		/// Returns an object GVCDDATI selected by a WHERE statement
		/// </summary>
		/// <param name="whereSql">The WHERE statement</param>
		/// <returns>Object of type GVCDDATI</returns>
		public GVCDDATI GetRow(string whereSql)
		{
			int totalRecordCount = -1;
			GVCDDATI[] rows = GetAsArray(whereSql, null, 0, 1, ref totalRecordCount);
			return rows.Length == 0 ? null : rows[0];
		}

		/// <summary>
		/// Returns an array containing the objects GVCDDATI selected by a WHERE statement
		/// and ordered by ORDER BY statement
		/// </summary>
		/// <param name="whereSql">The WHERE statement</param>
		/// <param name="orderBySql">The ORDER BY statement</param>
		/// <returns>Array of objects GVCDDATI</returns>
		public GVCDDATI[] GetAsArray(string whereSql, string orderBySql)
		{
			int totalRecordCount = -1;
			return GetAsArray(whereSql, orderBySql, 0, int.MaxValue, ref totalRecordCount);
		}

		/// <summary>
		/// Returns an array containing a subset of the objects GVCDDATI selected by 
		/// a WHERE statement and ordered by ORDER BY statement
		/// </summary>
		/// <param name="whereSql">The WHERE statement</param>
		/// <param name="orderBySql">The ORDER BY statement</param>
		/// <param name="startIndex">The index of the subset</param>
		/// <param name="Length">Length of the subset</param>
		/// <param name="totalRecordCount">Number of records</param>
		/// <returns>Array of objects GVCDDATI</returns>
		public virtual GVCDDATI[] GetAsArray(string whereSql, string orderBySql, int startIndex, int Length, ref int totalRecordCount)
		{
			using(IDataReader reader = _db.ExecuteReader(CreateGetCommand(whereSql, orderBySql)))
			{
				return MapRecords(reader, startIndex, Length, ref totalRecordCount);
			}
		}

		/// <summary>
		/// Returns a DataTable containing a subset of the objects GVCDDATI selected by 
		/// a WHERE statement and ordered by ORDER BY statement
		/// </summary>
		/// <param name="whereSql">The WHERE statement</param>
		/// <param name="orderBySql">The ORDER BY statement</param>
		/// <returns>DataTable of objects GVCDDATI</returns>
		public DataTable GetAsDataTable(string whereSql, string orderBySql)
		{
			int totalRecordCount = -1;
			return GetAsDataTable(whereSql, orderBySql, 0, int.MaxValue, ref totalRecordCount);
		}

		/// <summary>
		/// Returns a DataTable containing a subset of the objects GVCDDATI selected by 
		/// a WHERE statement and ordered by ORDER BY statement
		/// </summary>
		/// <param name="whereSql">The WHERE statement</param>
		/// <param name="orderBySql">The ORDER BY statement</param>
		/// <param name="startIndex">The index of the subset</param>
		/// <param name="length">Length of the subset</param>
		/// <param name="totalRecordCount">Number of records</param>
		/// <returns>DataTable of objects GVCDDATI</returns>
		public virtual DataTable GetAsDataTable(string whereSql, string orderBySql,	int startIndex, int length, ref int totalRecordCount)
		{
			using(IDataReader reader = _db.ExecuteReader(CreateGetCommand(whereSql, orderBySql)))
			{
				return MapRecordsToDataTable(reader, startIndex, length, ref totalRecordCount);
			}
		}

		/// <summary>
		/// Returns an IDbCommand to get the objects GVCDDATI selected by 
		/// a WHERE statement and ordered by ORDER BY statement
		/// </summary>
		/// <param name="whereSql">The WHERE statement</param>
		/// <param name="orderBySql">The ORDER BY statement</param>
		/// <returns>Istance of IDbCommand</returns>
		protected virtual IDbCommand CreateGetCommand(string whereSql, string orderBySql)
		{
			StringBuilder sql = new StringBuilder("SELECT ");
			sql.Append("IDOBJ, ");
			sql.Append("VALMINQUOTA, ");
			sql.Append("VALMAXQUOTA, ");
			sql.Append("VALMINAZIONE, ");
			sql.Append("VALMAXAZIONE, ");
			sql.Append("PERCENTUALE_CNP, ");
			sql.Append("PERCENTUALE_IVA, ");
			sql.Append("PERCENTUALE_PAT ");
			sql.Append("FROM GVCDDATI ");
			if(whereSql != null && whereSql.Length > 0)
				sql.Append(String.Format("WHERE {0} ", whereSql));
			if(orderBySql != null && orderBySql.Length > 0)
				sql.Append(String.Format("ORDER BY {0} ", orderBySql));
			return _db.CreateCommand(sql.ToString());
		}

		/// <summary>
		/// Returns an object GVCDDATI selected by a primary key
		/// </summary>
		/// <param name="IDOBJ">The primary key of the object</param>
		/// <returns>Object of type GVCDDATI</returns>
		public virtual GVCDDATI GetByPrimaryKey(System.Int32 IDOBJ)
		{
			string whereSql = "IDOBJ=" + _db.CreateSqlParameterName("IDOBJ");
			using(IDbCommand cmd = CreateGetCommand(whereSql, null))
			{
				AddParameter(cmd, "IDOBJ", IDOBJ);
				GVCDDATI[] tempArray = MapRecords(cmd);
				return tempArray.Length == 0 ? null : tempArray[0];
			}
		}


		/// <summary>
		/// Inserts in the Database an object GVCDDATI
		/// </summary>
		/// <param name="valore">The object to insert</param>
		public virtual void Insert(GVCDDATI valore)
		{
			System.Int32 id = -1;
			System.String sqlStr;

			sqlStr = "SELECT GVCDDATI_SEQ.NEXTVAL FROM DUAL";
			using(IDbCommand cmd = _db.CreateCommand(sqlStr))
			{
				id = Convert.ToInt32(cmd.ExecuteScalar());
			}

			sqlStr = "INSERT INTO GVCDDATI (" +
			"IDOBJ, " +
			"VALMINQUOTA, " +
			"VALMAXQUOTA, " +
			"VALMINAZIONE, " +
			"VALMAXAZIONE, " +
			"PERCENTUALE_CNP, " +
			"PERCENTUALE_IVA, " +
			"PERCENTUALE_PAT) " +
			"VALUES (" + id.ToString() + ", " +
			_db.CreateSqlParameterName("VALMINQUOTA") + ", " +
			_db.CreateSqlParameterName("VALMAXQUOTA") + ", " +
			_db.CreateSqlParameterName("VALMINAZIONE") + ", " +
			_db.CreateSqlParameterName("VALMAXAZIONE") + ", " +
			_db.CreateSqlParameterName("PERCENTUALE_CNP") + ", " +
			_db.CreateSqlParameterName("PERCENTUALE_IVA") + ", " +
			_db.CreateSqlParameterName("PERCENTUALE_PAT") + ")";
			using(IDbCommand cmd = _db.CreateCommand(sqlStr))
			{
				AddParameter(cmd, "VALMINQUOTA", valore.IsVALMINQUOTANull ? DBNull.Value : (object)valore.VALMINQUOTA);
				AddParameter(cmd, "VALMAXQUOTA", valore.IsVALMAXQUOTANull ? DBNull.Value : (object)valore.VALMAXQUOTA);
				AddParameter(cmd, "VALMINAZIONE", valore.IsVALMINAZIONENull ? DBNull.Value : (object)valore.VALMINAZIONE);
				AddParameter(cmd, "VALMAXAZIONE", valore.IsVALMAXAZIONENull ? DBNull.Value : (object)valore.VALMAXAZIONE);
				AddParameter(cmd, "PERCENTUALE_CNP", valore.IsPERCENTUALE_CNPNull ? DBNull.Value : (object)valore.PERCENTUALE_CNP);
				AddParameter(cmd, "PERCENTUALE_IVA", valore.IsPERCENTUALE_IVANull ? DBNull.Value : (object)valore.PERCENTUALE_IVA);
				AddParameter(cmd, "PERCENTUALE_PAT", valore.IsPERCENTUALE_PATNull ? DBNull.Value : (object)valore.PERCENTUALE_PAT);
				cmd.ExecuteScalar();
				valore.IDOBJ = id;
			}
		}

		/// <summary>
		/// Updates in the Database an object GVCDDATI
		/// </summary>
		/// <param name="valore">The object to update</param>
		/// <returns>true if success, otherwise false</returns>
		public virtual bool Update(GVCDDATI valore)
		{
			System.String sqlStr = "UPDATE GVCDDATI SET " +
				"VALMINQUOTA = " + _db.CreateSqlParameterName("VALMINQUOTA") + ", " +
				"VALMAXQUOTA = " + _db.CreateSqlParameterName("VALMAXQUOTA") + ", " +
				"VALMINAZIONE = " + _db.CreateSqlParameterName("VALMINAZIONE") + ", " +
				"VALMAXAZIONE = " + _db.CreateSqlParameterName("VALMAXAZIONE") + ", " +
				"PERCENTUALE_CNP = " + _db.CreateSqlParameterName("PERCENTUALE_CNP") + ", " +
				"PERCENTUALE_IVA = " + _db.CreateSqlParameterName("PERCENTUALE_IVA") + ", " +
				"PERCENTUALE_PAT = " + _db.CreateSqlParameterName("PERCENTUALE_PAT") +
				" WHERE " +
				"IDOBJ = " + _db.CreateSqlParameterName("IDOBJ");
			using(IDbCommand cmd = _db.CreateCommand(sqlStr))
			{
				AddParameter(cmd, "IDOBJ", valore.IDOBJ);
				AddParameter(cmd, "VALMINQUOTA", valore.IsVALMINQUOTANull ? DBNull.Value : (object)valore.VALMINQUOTA);
				AddParameter(cmd, "VALMAXQUOTA", valore.IsVALMAXQUOTANull ? DBNull.Value : (object)valore.VALMAXQUOTA);
				AddParameter(cmd, "VALMINAZIONE", valore.IsVALMINAZIONENull ? DBNull.Value : (object)valore.VALMINAZIONE);
				AddParameter(cmd, "VALMAXAZIONE", valore.IsVALMAXAZIONENull ? DBNull.Value : (object)valore.VALMAXAZIONE);
				AddParameter(cmd, "PERCENTUALE_CNP", valore.IsPERCENTUALE_CNPNull ? DBNull.Value : (object)valore.PERCENTUALE_CNP);
				AddParameter(cmd, "PERCENTUALE_IVA", valore.IsPERCENTUALE_IVANull ? DBNull.Value : (object)valore.PERCENTUALE_IVA);
				AddParameter(cmd, "PERCENTUALE_PAT", valore.IsPERCENTUALE_PATNull ? DBNull.Value : (object)valore.PERCENTUALE_PAT);
				return cmd.ExecuteNonQuery() != 0;
			}
		}

		/// <summary>
		/// Updates in the Database a DataTable of objects GVCDDATI
		/// </summary>
		/// <param name="table">The DataTable of objects GVCDDATI</param>
		public void Update(DataTable table)
		{
			Update(table, true);
		}

		/// <summary>
		/// Updates in the Database a DataTable of objects GVCDDATI
		/// </summary>
		/// <param name="table">The DataTable of objects GVCDDATI</param>
		/// <param name="acceptChanges">true to accept the changes, otherwise false</param>
		public virtual void Update(DataTable table, bool acceptChanges)
		{
			DataRowCollection rows = table.Rows;
			for(int i = rows.Count - 1; i >= 0; i--)
			{
				DataRow row = rows[i];
				switch(row.RowState)
				{
					case DataRowState.Added:
						Insert(MapRow(row));
						if(acceptChanges)
							row.AcceptChanges();
						break;

					case DataRowState.Deleted:
						row.RejectChanges();
						try
						{
							DeleteByPrimaryKey((System.Int32)row["IDOBJ"]);
						}
						finally
						{
							row.Delete();
						}
						if(acceptChanges)
							row.AcceptChanges();
						break;

				case DataRowState.Modified:
					Update(MapRow(row));
					if(acceptChanges)
						row.AcceptChanges();
					break;
				}
			}
		}

		/// <summary>
		/// Deletes from the Database an object GVCDDATI
		/// </summary>
		/// <param name="valore">The object to delete</param>
		/// <returns>true if success, otherwise false</returns>
		public bool Delete(GVCDDATI valore)
		{
			return DeleteByPrimaryKey(valore.IDOBJ);
		}

		/// <summary>
		/// Deletes from the Database an object GVCDDATI
		/// </summary>
		/// <param name="iDOBJ">The primary key of the object to delete</param>
		/// <returns>true if success, otherwise false</returns>
		public virtual bool DeleteByPrimaryKey(System.Int32 iDOBJ)
		{
			string whereSql = "IDOBJ=" + _db.CreateSqlParameterName("IDOBJ");
			using(IDbCommand cmd = CreateDeleteCommand(whereSql))
			{
				AddParameter(cmd, "IDOBJ" , iDOBJ);
				return cmd.ExecuteNonQuery() > 0;
			}
		}

		/// <summary>
		/// Deletes from the Database the objects GVCDDATI selected by a WHERE statement
		/// </summary>
		/// <param name="whereSql">The WHERE statement</param>
		/// <returns>The number of the deleted objects</returns>
		public int Delete(System.String whereSql)
		{
			return CreateDeleteCommand(whereSql).ExecuteNonQuery();
		}

		/// <summary>
		/// Returns an IDbCommand to delete the objects GVCDDATI selected by 
		/// a WHERE statement
		/// </summary>
		/// <param name="whereSql">The WHERE statement</param>
		/// <returns>Istance of IDbCommand</returns>
		protected virtual IDbCommand CreateDeleteCommand(string whereSql)
		{
			StringBuilder sql = new StringBuilder("DELETE FROM GVCDDATI");
			if(whereSql != null && whereSql.Length > 0)
				sql.Append(String.Format(" WHERE {0}", whereSql));
			return _db.CreateCommand(sql.ToString());
		}

		/// <summary>
		/// Deletes all the objects GVCDDATI
		/// </summary>
		/// <returns>The number of the deleted objects</returns>
		public int DeleteAll()
		{
			return Delete("");
		}

		/// <summary>
		/// Converts the IDataReader object to an array of type GVCDDATI
		/// </summary>
		/// <param name="command">The IDbCommand to execute</param>
		/// <returns>Array of type GVCDDATI</returns>
		protected GVCDDATI[] MapRecords(IDbCommand command)
		{
			using(IDataReader reader = _db.ExecuteReader(command))
			{
				return MapRecords(reader);
			}
		}

		/// <summary>
		/// Converts the IDataReader object to an array of type GVCDDATI
		/// </summary>
		/// <param name="reader">The IDataReader to convert</param>
		/// <returns>Array of type GVCDDATI</returns>
		protected GVCDDATI[] MapRecords(IDataReader reader)
		{
			int totalRecordCount = -1;
				return MapRecords(reader, 0, int.MaxValue, ref totalRecordCount);
		}

		/// <summary>
		/// Converts a subset of the IDataReader object to an array of type GVCDDATI
		/// </summary>
		/// <param name="reader">The IDataReader to convert</param>
		/// <param name="startIndex">The index of the subset</param>
		/// <param name="length">length of the subset</param>
		/// <param name="totalRecordCount">Number of records</param>
		/// <returns>Array of type GVCDDATI</returns>
		protected virtual GVCDDATI[] MapRecords(IDataReader reader, int startIndex, int length, ref int totalRecordCount)
		{
			if(startIndex < 0)
				throw new ArgumentOutOfRangeException("startIndex", startIndex, "StartIndex non può essere minore di zero.");
			if(length < 0)
				throw new ArgumentOutOfRangeException("length", length, "La lunghezza non può essere minore di zero.");

			int iDOBJColumnIndex = reader.GetOrdinal("IDOBJ");
			int vALMINQUOTAColumnIndex = reader.GetOrdinal("VALMINQUOTA");
			int vALMAXQUOTAColumnIndex = reader.GetOrdinal("VALMAXQUOTA");
			int vALMINAZIONEColumnIndex = reader.GetOrdinal("VALMINAZIONE");
			int vALMAXAZIONEColumnIndex = reader.GetOrdinal("VALMAXAZIONE");
			int pERCENTUALE_CNPColumnIndex = reader.GetOrdinal("PERCENTUALE_CNP");
			int pERCENTUALE_IVAColumnIndex = reader.GetOrdinal("PERCENTUALE_IVA");
			int pERCENTUALE_PATColumnIndex = reader.GetOrdinal("PERCENTUALE_PAT");

			System.Collections.ArrayList recordList = new System.Collections.ArrayList();
			int ri = -startIndex;

			while(reader.Read())
			{
				ri++;
				if(ri > 0 && ri <= length)
				{
					GVCDDATI record = new GVCDDATI();
					recordList.Add(record);
					record.IDOBJ = Convert.ToInt32(reader.GetValue(iDOBJColumnIndex));
					if(!reader.IsDBNull(vALMINQUOTAColumnIndex))
						record.VALMINQUOTA = Convert.ToDouble(reader.GetValue(vALMINQUOTAColumnIndex));
					if(!reader.IsDBNull(vALMAXQUOTAColumnIndex))
						record.VALMAXQUOTA = Convert.ToDouble(reader.GetValue(vALMAXQUOTAColumnIndex));
					if(!reader.IsDBNull(vALMINAZIONEColumnIndex))
						record.VALMINAZIONE = Convert.ToDouble(reader.GetValue(vALMINAZIONEColumnIndex));
					if(!reader.IsDBNull(vALMAXAZIONEColumnIndex))
						record.VALMAXAZIONE = Convert.ToDouble(reader.GetValue(vALMAXAZIONEColumnIndex));
					if(!reader.IsDBNull(pERCENTUALE_CNPColumnIndex))
						record.PERCENTUALE_CNP = Convert.ToDouble(reader.GetValue(pERCENTUALE_CNPColumnIndex));
					if(!reader.IsDBNull(pERCENTUALE_IVAColumnIndex))
						record.PERCENTUALE_IVA = Convert.ToDouble(reader.GetValue(pERCENTUALE_IVAColumnIndex));
					if(!reader.IsDBNull(pERCENTUALE_PATColumnIndex))
						record.PERCENTUALE_PAT = Convert.ToDouble(reader.GetValue(pERCENTUALE_PATColumnIndex));
					if(ri == length && totalRecordCount != 0)
						break;
				}
			}
			totalRecordCount = 0 == totalRecordCount ? ri + startIndex : -1;
			return (GVCDDATI[])(recordList.ToArray(typeof(GVCDDATI)));
		}

		/// <summary>
		/// Converts the IDataReader object to a DataTable
		/// </summary>
		/// <param name="command">The IDbCommand to execute</param>
		/// <returns>DataTable of objects GVCDDATI</returns>
		protected DataTable MapRecordsToDataTable(IDbCommand command)
		{
			using(IDataReader reader = _db.ExecuteReader(command))
			{
				return MapRecordsToDataTable(reader);
			}
		}

		/// <summary>
		/// Converts the IDataReader object to a DataTable
		/// </summary>
		/// <param name="reader">The IDataReader to convert</param>
		/// <returns>DataTable of objects GVCDDATI</returns>
		protected DataTable MapRecordsToDataTable(IDataReader reader)
		{
			int totalRecordCount = 0;
			return MapRecordsToDataTable(reader, 0, int.MaxValue, ref totalRecordCount);
		}

		/// <summary>
		/// Converts a subset of the IDataReader object to a DataTable
		/// </summary>
		/// <param name="reader">The IDataReader to convert</param>
		/// <param name="startIndex">The index of the subset</param>
		/// <param name="length">Length of the subset</param>
		/// <param name="totalRecordCount">Number of records</param>
		/// <returns>DataTable of objects GVCDDATI</returns>
		protected virtual DataTable MapRecordsToDataTable(IDataReader reader, int startIndex, int length, ref int totalRecordCount)
		{
			if(startIndex < 0)
				throw new ArgumentOutOfRangeException("startIndex", startIndex, "StartIndex non può essere minore di zero.");
			if(length < 0)
				throw new ArgumentOutOfRangeException("length", length, "La lunghezza non può essere minore di zero.");

			int columnCount = reader.FieldCount;
			int ri = -startIndex;

			DataTable dataTable = CreateDataTable();
			dataTable.BeginLoadData();
			object[] values = new object[columnCount];

			while(reader.Read())
			{
				ri++;
				if(ri > 0 && ri <= length)
				{
					reader.GetValues(values);
					dataTable.LoadDataRow(values, true);
					if(ri == length && totalRecordCount != 0)
						break;
				}
			}
			dataTable.EndLoadData();
			totalRecordCount = 0 == totalRecordCount ? ri + startIndex : -1;
			return dataTable;
		}

		/// <summary>
		/// Converts a DataRow to an object GVCDDATI
		/// </summary>
		/// <param name="row">The DataRow to convert</param>
		/// <returns>An object GVCDDATI</returns>
		protected virtual GVCDDATI MapRow(DataRow row)
		{
			GVCDDATI mappedObject = new GVCDDATI();
			DataTable dataTable = row.Table;
			DataColumn dataColumn;
			//Campo "IDOBJ"
			dataColumn = dataTable.Columns["IDOBJ"];
			if(!row.IsNull(dataColumn))
				mappedObject.IDOBJ = (System.Int32)row[dataColumn];
			//Campo "VALMINQUOTA"
			dataColumn = dataTable.Columns["VALMINQUOTA"];
			if(!row.IsNull(dataColumn))
				mappedObject.VALMINQUOTA = (System.Double)row[dataColumn];
			//Campo "VALMAXQUOTA"
			dataColumn = dataTable.Columns["VALMAXQUOTA"];
			if(!row.IsNull(dataColumn))
				mappedObject.VALMAXQUOTA = (System.Double)row[dataColumn];
			//Campo "VALMINAZIONE"
			dataColumn = dataTable.Columns["VALMINAZIONE"];
			if(!row.IsNull(dataColumn))
				mappedObject.VALMINAZIONE = (System.Double)row[dataColumn];
			//Campo "VALMAXAZIONE"
			dataColumn = dataTable.Columns["VALMAXAZIONE"];
			if(!row.IsNull(dataColumn))
				mappedObject.VALMAXAZIONE = (System.Double)row[dataColumn];
			//Campo "PERCENTUALE_CNP"
			dataColumn = dataTable.Columns["PERCENTUALE_CNP"];
			if(!row.IsNull(dataColumn))
				mappedObject.PERCENTUALE_CNP = (System.Double)row[dataColumn];
			//Campo "PERCENTUALE_IVA"
			dataColumn = dataTable.Columns["PERCENTUALE_IVA"];
			if(!row.IsNull(dataColumn))
				mappedObject.PERCENTUALE_IVA = (System.Double)row[dataColumn];
			//Campo "PERCENTUALE_PAT"
			dataColumn = dataTable.Columns["PERCENTUALE_PAT"];
			if(!row.IsNull(dataColumn))
				mappedObject.PERCENTUALE_PAT = (System.Double)row[dataColumn];
			return mappedObject;
		}

		/// <summary>
		/// Creates a DataTable to store the objects GVCDDATI
		/// </summary>
		/// <returns>A DataTable</returns>
		protected virtual DataTable CreateDataTable()
		{
			DataTable dataTable = new DataTable();
			dataTable.TableName = "GVCDDATI";
			DataColumn dataColumn;
			dataColumn = dataTable.Columns.Add("IDOBJ", typeof(System.Int32));
			dataColumn.AllowDBNull = false;
			dataColumn.ReadOnly = true;
			dataColumn.Unique = true;
			dataColumn.AutoIncrement = true;
			dataColumn = dataTable.Columns.Add("VALMINQUOTA", typeof(System.Double));
			dataColumn.AllowDBNull = true;
			dataColumn.ReadOnly = false;
			dataColumn.Unique = false;
			dataColumn.AutoIncrement = false;
			dataColumn = dataTable.Columns.Add("VALMAXQUOTA", typeof(System.Double));
			dataColumn.AllowDBNull = true;
			dataColumn.ReadOnly = false;
			dataColumn.Unique = false;
			dataColumn.AutoIncrement = false;
			dataColumn = dataTable.Columns.Add("VALMINAZIONE", typeof(System.Double));
			dataColumn.AllowDBNull = true;
			dataColumn.ReadOnly = false;
			dataColumn.Unique = false;
			dataColumn.AutoIncrement = false;
			dataColumn = dataTable.Columns.Add("VALMAXAZIONE", typeof(System.Double));
			dataColumn.AllowDBNull = true;
			dataColumn.ReadOnly = false;
			dataColumn.Unique = false;
			dataColumn.AutoIncrement = false;
			dataColumn = dataTable.Columns.Add("PERCENTUALE_CNP", typeof(System.Double));
			dataColumn.AllowDBNull = true;
			dataColumn.ReadOnly = false;
			dataColumn.Unique = false;
			dataColumn.AutoIncrement = false;
			dataColumn = dataTable.Columns.Add("PERCENTUALE_IVA", typeof(System.Double));
			dataColumn.AllowDBNull = true;
			dataColumn.ReadOnly = false;
			dataColumn.Unique = false;
			dataColumn.AutoIncrement = false;
			dataColumn = dataTable.Columns.Add("PERCENTUALE_PAT", typeof(System.Double));
			dataColumn.AllowDBNull = true;
			dataColumn.ReadOnly = false;
			dataColumn.Unique = false;
			dataColumn.AutoIncrement = false;
			return dataTable;
		}

		/// <summary>
		/// Adds to an IDbCommand a IDbDataParameter
		/// </summary>
		/// <param name="cmd">The IDbCommand</param>
		/// <param name="paramName">The parameter name to add</param>
		/// <param name="valore">The value of the parameter</param>
		/// <returns>A IDbDataParameter</returns>
		protected virtual IDbDataParameter AddParameter(IDbCommand cmd, string paramName, object valore)
		{
			IDbDataParameter parameter;
			switch(paramName)
			{
				case "IDOBJ":
					parameter = _db.AddParameter(cmd, paramName, DbType.Int32, valore);
					break;

				case "VALMINQUOTA":
					parameter = _db.AddParameter(cmd, paramName, DbType.Double, valore);
					break;

				case "VALMAXQUOTA":
					parameter = _db.AddParameter(cmd, paramName, DbType.Double, valore);
					break;

				case "VALMINAZIONE":
					parameter = _db.AddParameter(cmd, paramName, DbType.Double, valore);
					break;

				case "VALMAXAZIONE":
					parameter = _db.AddParameter(cmd, paramName, DbType.Double, valore);
					break;

				case "PERCENTUALE_CNP":
					parameter = _db.AddParameter(cmd, paramName, DbType.Double, valore);
					break;

				case "PERCENTUALE_IVA":
					parameter = _db.AddParameter(cmd, paramName, DbType.Double, valore);
					break;

				case "PERCENTUALE_PAT":
					parameter = _db.AddParameter(cmd, paramName, DbType.Double, valore);
					break;

				default:
					throw new ArgumentException("Nome parametro sconosciuto (" + paramName + ").");
			}
			return parameter;
		}
	}
}
