//
//Generated by gvc at 06/03/2009 13.55.13
//

using System;
using System.Data;
using System.Text;

namespace it.dedagroup.GVC.Repository.rtier.Service
{
	/// <summary>
	/// Data Access Layer for the object GVCTADESIONI
	/// </summary>
	public partial class GVCTADESIONICollection
	{
        public GVCTADESIONI[] GetListAdesioniByIdRegistro(int idRegistro)
        {
            string where = String.Format(it.dedagroup.GVC.Repository.rtier.Queries.Oracle.Formats.FIELD_EQUALS_NUMBER,
                                            GVCTADESIONICollection.IDOBJ_REGISTROColumnName,
                                            idRegistro);
            return GetAsArray(where, String.Concat(GVCTADESIONICollection.DATA_INIZIO_ADESIONEColumnName, " DESC "));
        }
	}
}
