//
//Generated by DELTADATOR\GS0445 at 05/08/2009 14.41.04
//

using System;

namespace it.dedagroup.GVC.Repository.rtier.Service
{
	/// <summary>
	/// Description of GVCVCOOPERATIVEATTIVE
	/// </summary>
	public partial class GVCVCOOPERATIVEATTIVE
	{
		private System.String _dENOMINAZIONE;
		private System.Boolean _dENOMINAZIONENull = true;
		private System.String _cODICE_FISCALE;
		private System.Boolean _cODICE_FISCALENull = true;
		private System.Int32 _iDOBJ;
		private System.String _nUMERO_REA;
		private System.Boolean _nUMERO_REANull = true;
		private System.Double _rEANUMERIC;
		private System.Boolean _rEANUMERICNull = true;
		private System.DateTime _dATA_DETERMINA;
		private System.Boolean _dATA_DETERMINANull = true;
		private System.String _nUMERO_DETERMINA;
		private System.Boolean _nUMERO_DETERMINANull = true;
		private System.Int32 _iDOBJ_STATO;
		private System.Boolean _iDOBJ_STATONull = true;

		/// <summary>
		/// Default constructor
		/// </summary>
		public GVCVCOOPERATIVEATTIVE(){}

		/// <summary>
		/// Value of field DENOMINAZIONE
		/// </summary>
		public System.String DENOMINAZIONE
		{
			get
			{
				if(IsDENOMINAZIONENull)
					throw new InvalidOperationException("Impossibile leggere il dato in quanto vale DBNull.");
				return _dENOMINAZIONE;
			}
			set
			{
				_dENOMINAZIONENull = false;
				_dENOMINAZIONE = value;
			}
		}

		/// <summary>
		/// Return true if field is null, otherwise false.
		/// </summary>
		public bool IsDENOMINAZIONENull
		{
			get
			{
				return _dENOMINAZIONENull;
			}
			set
			{
				_dENOMINAZIONENull = value;
			}
		}

		/// <summary>
		///  This property is intend to use with string and integer fields 
		///  that can contain nullable values. 
		///  It is read only. 
		/// </summary>
		/// <returns>The value of the field or String.Empty/-1</returns>
		public System.String DENOMINAZIONESafe
		{
			get
			{
				if (IsDENOMINAZIONENull)
					return System.String.Empty;
				return DENOMINAZIONE;
			}
		}

		/// <summary>
		/// Value of field CODICE_FISCALE
		/// </summary>
		public System.String CODICE_FISCALE
		{
			get
			{
				if(IsCODICE_FISCALENull)
					throw new InvalidOperationException("Impossibile leggere il dato in quanto vale DBNull.");
				return _cODICE_FISCALE;
			}
			set
			{
				_cODICE_FISCALENull = false;
				_cODICE_FISCALE = value;
			}
		}

		/// <summary>
		/// Return true if field is null, otherwise false.
		/// </summary>
		public bool IsCODICE_FISCALENull
		{
			get
			{
				return _cODICE_FISCALENull;
			}
			set
			{
				_cODICE_FISCALENull = value;
			}
		}

		/// <summary>
		///  This property is intend to use with string and integer fields 
		///  that can contain nullable values. 
		///  It is read only. 
		/// </summary>
		/// <returns>The value of the field or String.Empty/-1</returns>
		public System.String CODICE_FISCALESafe
		{
			get
			{
				if (IsCODICE_FISCALENull)
					return System.String.Empty;
				return CODICE_FISCALE;
			}
		}

		/// <summary>
		/// Value of field IDOBJ
		/// The field is mandatory.
		/// </summary>
		public System.Int32 IDOBJ
		{
			get
			{
				return _iDOBJ;
			}
			set
			{
				_iDOBJ = value;
			}
		}

		/// <summary>
		/// Value of field NUMERO_REA
		/// </summary>
		public System.String NUMERO_REA
		{
			get
			{
				if(IsNUMERO_REANull)
					throw new InvalidOperationException("Impossibile leggere il dato in quanto vale DBNull.");
				return _nUMERO_REA;
			}
			set
			{
				_nUMERO_REANull = false;
				_nUMERO_REA = value;
			}
		}

		/// <summary>
		/// Return true if field is null, otherwise false.
		/// </summary>
		public bool IsNUMERO_REANull
		{
			get
			{
				return _nUMERO_REANull;
			}
			set
			{
				_nUMERO_REANull = value;
			}
		}

		/// <summary>
		///  This property is intend to use with string and integer fields 
		///  that can contain nullable values. 
		///  It is read only. 
		/// </summary>
		/// <returns>The value of the field or String.Empty/-1</returns>
		public System.String NUMERO_REASafe
		{
			get
			{
				if (IsNUMERO_REANull)
					return System.String.Empty;
				return NUMERO_REA;
			}
		}

		/// <summary>
		/// Value of field REANUMERIC
		/// </summary>
		public System.Double REANUMERIC
		{
			get
			{
				if(IsREANUMERICNull)
					throw new InvalidOperationException("Impossibile leggere il dato in quanto vale DBNull.");
				return _rEANUMERIC;
			}
			set
			{
				_rEANUMERICNull = false;
				_rEANUMERIC = value;
			}
		}

		/// <summary>
		/// Return true if field is null, otherwise false.
		/// </summary>
		public bool IsREANUMERICNull
		{
			get
			{
				return _rEANUMERICNull;
			}
			set
			{
				_rEANUMERICNull = value;
			}
		}

		/// <summary>
		/// Value of field DATA_DETERMINA
		/// </summary>
		public System.DateTime DATA_DETERMINA
		{
			get
			{
				if(IsDATA_DETERMINANull)
					throw new InvalidOperationException("Impossibile leggere il dato in quanto vale DBNull.");
				return _dATA_DETERMINA;
			}
			set
			{
				_dATA_DETERMINANull = false;
				_dATA_DETERMINA = value;
			}
		}

		/// <summary>
		/// Return true if field is null, otherwise false.
		/// </summary>
		public bool IsDATA_DETERMINANull
		{
			get
			{
				return _dATA_DETERMINANull;
			}
			set
			{
				_dATA_DETERMINANull = value;
			}
		}

		/// <summary>
		/// Value of field NUMERO_DETERMINA
		/// </summary>
		public System.String NUMERO_DETERMINA
		{
			get
			{
				if(IsNUMERO_DETERMINANull)
					throw new InvalidOperationException("Impossibile leggere il dato in quanto vale DBNull.");
				return _nUMERO_DETERMINA;
			}
			set
			{
				_nUMERO_DETERMINANull = false;
				_nUMERO_DETERMINA = value;
			}
		}

		/// <summary>
		/// Return true if field is null, otherwise false.
		/// </summary>
		public bool IsNUMERO_DETERMINANull
		{
			get
			{
				return _nUMERO_DETERMINANull;
			}
			set
			{
				_nUMERO_DETERMINANull = value;
			}
		}

		/// <summary>
		///  This property is intend to use with string and integer fields 
		///  that can contain nullable values. 
		///  It is read only. 
		/// </summary>
		/// <returns>The value of the field or String.Empty/-1</returns>
		public System.String NUMERO_DETERMINASafe
		{
			get
			{
				if (IsNUMERO_DETERMINANull)
					return System.String.Empty;
				return NUMERO_DETERMINA;
			}
		}

		/// <summary>
		/// Value of field IDOBJ_STATO
		/// </summary>
		public System.Int32 IDOBJ_STATO
		{
			get
			{
				if(IsIDOBJ_STATONull)
					throw new InvalidOperationException("Impossibile leggere il dato in quanto vale DBNull.");
				return _iDOBJ_STATO;
			}
			set
			{
				_iDOBJ_STATONull = false;
				_iDOBJ_STATO = value;
			}
		}

		/// <summary>
		/// Return true if field is null, otherwise false.
		/// </summary>
		public bool IsIDOBJ_STATONull
		{
			get
			{
				return _iDOBJ_STATONull;
			}
			set
			{
				_iDOBJ_STATONull = value;
			}
		}

		/// <summary>
		///  This property is intend to use with string and integer fields 
		///  that can contain nullable values. 
		///  It is read only. 
		/// </summary>
		/// <returns>The value of the field or String.Empty/-1</returns>
		public System.Int32 IDOBJ_STATOSafe
		{
			get
			{
				if (IsIDOBJ_STATONull)
					return -1;
				return IDOBJ_STATO;
			}
		}

	}
}